/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSaidaRouteImport } from './routes/app.saida'
import { Route as AppCondutoresRouteImport } from './routes/app.condutores'
import { Route as AppAbastecimentosIndexRouteImport } from './routes/app.abastecimentos.index'
import { Route as AppRetornoViaturaIdRouteImport } from './routes/app.retorno.$viaturaId'
import { Route as AppAbastecimentosNovoRouteImport } from './routes/app.abastecimentos.novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSaidaRoute = AppSaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => AppRoute,
} as any)
const AppCondutoresRoute = AppCondutoresRouteImport.update({
  id: '/condutores',
  path: '/condutores',
  getParentRoute: () => AppRoute,
} as any)
const AppAbastecimentosIndexRoute = AppAbastecimentosIndexRouteImport.update({
  id: '/abastecimentos/',
  path: '/abastecimentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppRetornoViaturaIdRoute = AppRetornoViaturaIdRouteImport.update({
  id: '/retorno/$viaturaId',
  path: '/retorno/$viaturaId',
  getParentRoute: () => AppRoute,
} as any)
const AppAbastecimentosNovoRoute = AppAbastecimentosNovoRouteImport.update({
  id: '/abastecimentos/novo',
  path: '/abastecimentos/novo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/condutores': typeof AppCondutoresRoute
  '/app/saida': typeof AppSaidaRoute
  '/app/': typeof AppIndexRoute
  '/app/abastecimentos/novo': typeof AppAbastecimentosNovoRoute
  '/app/retorno/$viaturaId': typeof AppRetornoViaturaIdRoute
  '/app/abastecimentos/': typeof AppAbastecimentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/condutores': typeof AppCondutoresRoute
  '/app/saida': typeof AppSaidaRoute
  '/app': typeof AppIndexRoute
  '/app/abastecimentos/novo': typeof AppAbastecimentosNovoRoute
  '/app/retorno/$viaturaId': typeof AppRetornoViaturaIdRoute
  '/app/abastecimentos': typeof AppAbastecimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/condutores': typeof AppCondutoresRoute
  '/app/saida': typeof AppSaidaRoute
  '/app/': typeof AppIndexRoute
  '/app/abastecimentos/novo': typeof AppAbastecimentosNovoRoute
  '/app/retorno/$viaturaId': typeof AppRetornoViaturaIdRoute
  '/app/abastecimentos/': typeof AppAbastecimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/condutores'
    | '/app/saida'
    | '/app/'
    | '/app/abastecimentos/novo'
    | '/app/retorno/$viaturaId'
    | '/app/abastecimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/condutores'
    | '/app/saida'
    | '/app'
    | '/app/abastecimentos/novo'
    | '/app/retorno/$viaturaId'
    | '/app/abastecimentos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/condutores'
    | '/app/saida'
    | '/app/'
    | '/app/abastecimentos/novo'
    | '/app/retorno/$viaturaId'
    | '/app/abastecimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saida': {
      id: '/app/saida'
      path: '/saida'
      fullPath: '/app/saida'
      preLoaderRoute: typeof AppSaidaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/condutores': {
      id: '/app/condutores'
      path: '/condutores'
      fullPath: '/app/condutores'
      preLoaderRoute: typeof AppCondutoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/abastecimentos/': {
      id: '/app/abastecimentos/'
      path: '/abastecimentos'
      fullPath: '/app/abastecimentos/'
      preLoaderRoute: typeof AppAbastecimentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retorno/$viaturaId': {
      id: '/app/retorno/$viaturaId'
      path: '/retorno/$viaturaId'
      fullPath: '/app/retorno/$viaturaId'
      preLoaderRoute: typeof AppRetornoViaturaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/abastecimentos/novo': {
      id: '/app/abastecimentos/novo'
      path: '/abastecimentos/novo'
      fullPath: '/app/abastecimentos/novo'
      preLoaderRoute: typeof AppAbastecimentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCondutoresRoute: typeof AppCondutoresRoute
  AppSaidaRoute: typeof AppSaidaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAbastecimentosNovoRoute: typeof AppAbastecimentosNovoRoute
  AppRetornoViaturaIdRoute: typeof AppRetornoViaturaIdRoute
  AppAbastecimentosIndexRoute: typeof AppAbastecimentosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCondutoresRoute: AppCondutoresRoute,
  AppSaidaRoute: AppSaidaRoute,
  AppIndexRoute: AppIndexRoute,
  AppAbastecimentosNovoRoute: AppAbastecimentosNovoRoute,
  AppRetornoViaturaIdRoute: AppRetornoViaturaIdRoute,
  AppAbastecimentosIndexRoute: AppAbastecimentosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
